Usage:

  ueb03 -h | ueb03 --help
  
    prints this help and exits
  
  - or -
  
  ueb03 NUM1 NUM2 OPERATION [NUM OPERATION] ...
  
    provides a simple calculator using a postfix notation. A call consists of
    two numbers and an operation optionally followed by an arbitrary number
    of number-operation pairs.
  
    NUM1, NUM2 and NUM:
      any integer (negative, positive and zero)
  
    NUM is treated in the same way as NUM2 whereas NUM1 in this case is the
    result of the previous operation.
  
    OPERATION:
      ADD -> adds NUM1 and NUM2
      SUB -> subtracts NUM2 from NUM1
      MUL -> multiplies NUM1 and NUM2
      DIV -> divides NUM1 by NUM2 and returns the integer result
      MOD -> divides NUM1 by NUM2 and returns the integer remainder
      EXP -> raises NUM1 to the power of NUM2
  
  At the end of a successful call the history of all intermediate calculations 
  is printed out to stderr.
